import { Inter } from "next/font/google";
// import "./globals.css";
import Footer from "../components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Tanvir's Portfolio",
//   description: "Generated by create next app",
// };

export default function PageLayout({ children }) {
  return (
    <div className="p-4">
      {children}
      <Footer />
    </div>
  );
}
